CPPFLAGS = -I..
CFLAGS = -shared -Wall -Wextra -fPIC -g3 -O0
CXXFLAGS = $(CFLAGS)
LDFLAGS = -L../spitz -lspitz

all: pi.so picpp.so

pi.so: pi.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ $^ $(LDFLAGS)

picpp.so: pi.cpp
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o $@ $^ $(LDFLAGS)

test: pi.so picpp.so
	# Set some environment variables
	LD_LIBRARY_PATH=$$PWD/../spitz PATH=$$PATH:$$PWD/../spitz \
			mpirun -np 3 spitz $$PWD/pi.so    10000
	LD_LIBRARY_PATH=$$PWD/../spitz PATH=$$PATH:$$PWD/../spitz \
			mpirun -np 3 spitz $$PWD/picpp.so 10000

clean:
	-rm -f pi.so picpp.so

prefix = /usr/local
datadir = $(prefix)/share/spitz

install:
	install -m 0755 -d $(DESTDIR)$(datadir)
	install -m 0644 pi.c pi.cpp Makefile $(DESTDIR)$(datadir)
